FROM data:awkward_armadillo

LABEL author="Juan Pedro Perez"
LABEL email="jp.perez.alcantara@pm.me"

WORKDIR /

USER root

# Actualizar apt.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade && \
    apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade && \
    apt-get install -y postgresql-client gdal-bin libgdal-dev && \
    apt-get autoremove -y

# Actualizar pip a una versión específica.
RUN pip install --upgrade pip==26.0.1

# Instalar dependencias Python de proyecto.
COPY assets/python/requirements.txt /requirements.txt
RUN pip install --upgrade -r /requirements.txt

# Instalar la versión de bindings GDAL correcta para Python.
RUN pip install "GDAL==$(gdal-config --version).*"

USER vscode

WORKDIR /workspace/api
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]