FROM node:trixie

LABEL author="Juan Pedro Perez"
LABEL email="jp.perez.alcantara@pm.me"

WORKDIR /

USER root

# Actualizar apt.
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade && \
    apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade && \
    apt-get autoremove -y

RUN npm install -g vite create-vite@9.0.3

USER node

CMD ["sleep", "infinity"]
