# Connection keep alive timeout [default: 75]
keep_alive: 75

# The socket address to bind [default: 0.0.0.0:3000]
listen_addresses: '0.0.0.0:3000'

# Number of web server workers
worker_processes: 4

# Amount of memory (in MB) to use for caching tiles [default: 512, 0 to disable]
cache_size_mb: 2048

# Sending/Acting on CORS headers can be completely disabled via `cors: false`
cors: true

# Database configuration. This can also be a list of PG configs.
postgres:
  connection_string: $DATABASE_URL
  default_srid: 3857

  auto_publish:
    from_schemas:
      - climagen
