networks:
  network:
    name: clima-gen

volumes:
  postgres-data:
    name: clima-gen-postgres-data
    external: true
  letsencrypt-data:
    name: clima-gen-letsencrypt-data
    external: true
  certbot-www:
    name: clima-gen-certbot-www
    external: true

services:
  # -------------------
  #
  # Nginx.
  #
  # -------------------
  nginx:
    image: clima-gen-nginx
    container_name: clima-gen-nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./assets/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/nginx/runtime-config.json:/app/runtime-config.json
      - letsencrypt-data:/etc/letsencrypt
      - certbot-www:/var/www/certbot

    networks:
      - network

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/nginx-healthz >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s


  # -------------------
  #
  # API.
  #
  # -------------------
  api:
    image: clima-gen-api
    container_name: clima-gen-api
    env_file:
      - assets/env

    networks:
      - network

    depends_on:
      postgres:
        condition: service_healthy

  # -------------------
  #
  # PostgreSQL.
  #
  # -------------------
  postgres:
    image: clima-gen-postgres
    container_name: clima-gen-postgres
    shm_size: "3GB"
    env_file:
      - assets/env

    volumes:
      - postgres-data:/var/lib/postgresql/
      - ./assets/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro

    networks:
      - network

    healthcheck:
      test: PGPASSWORD="${PGPASSWORD}" psql -U postgres -tAc 'select 1' -d postgres
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  # -------------------
  #
  # MapLibre Martin.
  #
  # -------------------
  martin:
    image: ghcr.io/maplibre/martin:v0.16.0
    container_name: clima-gen-martin
    restart: unless-stopped
    command: ["--config", "/config.yaml"]
    env_file:
      - ./assets/env

    networks:
      - network

    volumes:
      - ./assets/martin/config.yaml:/config.yaml

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:3000 >/dev/null || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s


  # -------------------
  #
  # Certbot.
  #
  # -------------------
  certbot:
    image: certbot/certbot:v2.11.0
    container_name: clima-gen-certbot
    restart: unless-stopped

    volumes:
      - letsencrypt-data:/etc/letsencrypt
      - certbot-www:/var/www/certbot

    pid: "service:nginx"

    entrypoint: /bin/sh
    command: >
      -c 'while :; do
      certbot renew --webroot -w /var/www/certbot --quiet
      --deploy-hook "kill -HUP 1";
      sleep 1d;
      done'

    depends_on:
      nginx:
        condition: service_healthy
      postgres:
        condition: service_healthy
